"""FastAPI backend for the Contract Rules skill UI."""

import json
import os
import re
import subprocess
import tempfile
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from fastapi import FastAPI, HTTPException, UploadFile, File, Form
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

app = FastAPI(title="Contract Rules API", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://localhost:3000"],
    allow_methods=["*"],
    allow_headers=["*"],
)

IS_VERCEL = bool(os.environ.get("VERCEL"))
SKILL_ROOT = Path(__file__).resolve().parent.parent
RULES_FILE = SKILL_ROOT / "references" / "rules_schema.md"

# On Vercel, writable storage is /tmp only
_TMP_RULES = Path("/tmp/rules_schema.md")
_TMP_EXTRACTIONS = Path("/tmp/extractions.json")

if IS_VERCEL:
    EXTRACTIONS_FILE = _TMP_EXTRACTIONS
    if not _TMP_RULES.exists() and RULES_FILE.exists():
        _TMP_RULES.write_text(RULES_FILE.read_text(encoding="utf-8"), encoding="utf-8")
    RULES_FILE = _TMP_RULES
else:
    EXTRACTIONS_FILE = SKILL_ROOT / "api" / "extractions.json"


def _load_extractions() -> list:
    if EXTRACTIONS_FILE.exists():
        return json.loads(EXTRACTIONS_FILE.read_text(encoding="utf-8"))
    return []


def _save_extractions(data: list):
    EXTRACTIONS_FILE.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def _parse_rules_md() -> dict:
    """Parse the rules_schema.md file into structured data."""
    if not RULES_FILE.exists():
        return {"populated": False, "rules": [], "meta": {}}

    content = RULES_FILE.read_text(encoding="utf-8")

    if "auto-generated by the extraction script" in content and "To populate it" in content:
        return {"populated": False, "rules": [], "meta": {}}

    meta = {}
    for key in ["Company", "Type", "Version", "Extracted", "Summary", "Total rules"]:
        match = re.search(rf"\*\*{key}:\*\*\s*(.+?)(?:\s\s|$)", content)
        if match:
            meta[key.lower().replace(" ", "_")] = match.group(1).strip()

    skill_match = re.search(r"# Rules Schema — (.+)", content)
    if skill_match:
        meta["skill_name"] = skill_match.group(1).strip()

    rules = []
    rule_blocks = re.findall(
        r"### \[(\w+)\] — (\w+) · (\w+)\n"
        r"\*\*Rule:\*\* (.+?)\n"
        r"\*\*Conditions:\*\* (.+?)\n"
        r"\*\*Exceptions:\*\* (.+?)(?:\n\n|\Z)",
        content,
        re.DOTALL,
    )
    for rid, category, priority, rule, conditions, exceptions in rule_blocks:
        rules.append({
            "id": rid,
            "category": category,
            "priority": priority,
            "rule": rule.strip(),
            "conditions": conditions.strip(),
            "exceptions": exceptions.strip() if exceptions.strip() != "None" else None,
        })

    return {"populated": True, "rules": rules, "meta": meta}


@app.get("/api/health")
async def health():
    return {"status": "ok", "timestamp": datetime.now(timezone.utc).isoformat()}


@app.get("/api/rules")
async def get_rules(category: Optional[str] = None, priority: Optional[str] = None):
    data = _parse_rules_md()
    rules = data["rules"]
    if category:
        rules = [r for r in rules if r["category"] == category]
    if priority:
        rules = [r for r in rules if r["priority"] == priority]
    return {
        "populated": data["populated"],
        "meta": data["meta"],
        "rules": rules,
        "total": len(rules),
    }


@app.get("/api/stats")
async def get_stats():
    data = _parse_rules_md()
    rules = data["rules"]

    by_priority = {"alta": 0, "media": 0, "baixa": 0}
    by_category = {}
    for r in rules:
        p = r.get("priority", "media")
        by_priority[p] = by_priority.get(p, 0) + 1
        c = r.get("category", "other")
        by_category[c] = by_category.get(c, 0) + 1

    extractions = _load_extractions()

    return {
        "total_rules": len(rules),
        "populated": data["populated"],
        "by_priority": by_priority,
        "by_category": by_category,
        "meta": data["meta"],
        "total_extractions": len(extractions),
        "last_extraction": extractions[-1] if extractions else None,
    }


@app.get("/api/extractions")
async def list_extractions():
    return {"items": _load_extractions()}


class ExtractRequest(BaseModel):
    company: Optional[str] = None
    central_type: str = "geral"


@app.post("/api/extract")
async def extract_rules(
    file: UploadFile = File(...),
    company: str = Form(""),
    central_type: str = Form("geral"),
):
    if not os.environ.get("ANTHROPIC_API_KEY"):
        raise HTTPException(400, "ANTHROPIC_API_KEY não configurada no servidor.")

    content = await file.read()
    try:
        text = content.decode("utf-8")
    except UnicodeDecodeError:
        text = content.decode("latin-1")

    if not text.strip():
        raise HTTPException(400, "Arquivo vazio.")

    with tempfile.NamedTemporaryFile(mode="w", suffix=".txt", delete=False, encoding="utf-8") as f:
        f.write(text)
        tmp_path = f.name

    try:
        cmd = ["python3", str(SKILL_ROOT / "scripts" / "extract_rules.py"), "--input", tmp_path]
        if company:
            cmd.extend(["--company", company])
        cmd.extend(["--type", central_type])

        result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)

        if result.returncode != 0:
            raise HTTPException(500, f"Erro na extração: {result.stderr}")

        data = _parse_rules_md()

        extraction_log = {
            "id": str(uuid.uuid4()),
            "filename": file.filename,
            "company": company or data.get("meta", {}).get("company", "unknown"),
            "central_type": central_type,
            "total_rules": len(data.get("rules", [])),
            "extracted_at": datetime.now(timezone.utc).isoformat(),
        }
        extractions = _load_extractions()
        extractions.append(extraction_log)
        _save_extractions(extractions)

        return {
            "message": f"{len(data.get('rules', []))} regras extraídas com sucesso.",
            "data": data,
            "log": extraction_log,
        }
    finally:
        os.unlink(tmp_path)


class TestRequest(BaseModel):
    question: str


@app.post("/api/test")
async def test_rules(body: TestRequest):
    """Test a customer question against loaded rules using Claude."""
    if not os.environ.get("ANTHROPIC_API_KEY"):
        raise HTTPException(400, "ANTHROPIC_API_KEY não configurada.")

    data = _parse_rules_md()
    if not data["populated"]:
        raise HTTPException(400, "Nenhuma regra carregada. Extraia um contrato primeiro.")

    try:
        import anthropic
    except ImportError:
        raise HTTPException(500, "Pacote 'anthropic' não instalado.")

    rules_text = RULES_FILE.read_text(encoding="utf-8")
    skill_text = (SKILL_ROOT / "SKILL.md").read_text(encoding="utf-8")

    client = anthropic.Anthropic()
    message = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=2048,
        system=f"{skill_text}\n\n---\n\nRULES LOADED:\n{rules_text}",
        messages=[{"role": "user", "content": body.question}],
    )

    response_text = message.content[0].text

    matched_ids = re.findall(r"\[R\d+\]", response_text)
    matched_rules = [r for r in data["rules"] if f"[{r['id']}]" in matched_ids]

    return {
        "question": body.question,
        "response": response_text,
        "matched_rules": matched_rules,
        "model": "claude-sonnet-4-20250514",
    }


@app.put("/api/rules/{rule_id}")
async def update_rule(rule_id: str, body: dict):
    """Update a single rule in rules_schema.md."""
    if not RULES_FILE.exists():
        raise HTTPException(404, "Arquivo de regras não encontrado.")

    content = RULES_FILE.read_text(encoding="utf-8")

    pattern = (
        rf"(### \[{rule_id}\] — )\w+( · )\w+\n"
        rf"\*\*Rule:\*\* .+?\n"
        rf"\*\*Conditions:\*\* .+?\n"
        rf"\*\*Exceptions:\*\* .+?"
    )

    match = re.search(pattern, content, re.DOTALL)
    if not match:
        raise HTTPException(404, f"Regra {rule_id} não encontrada.")

    category = body.get("category", "other")
    priority = body.get("priority", "media")
    rule = body.get("rule", "")
    conditions = body.get("conditions", "N/A")
    exceptions = body.get("exceptions") or "None"

    replacement = (
        f"### [{rule_id}] — {category} · {priority}\n"
        f"**Rule:** {rule}\n"
        f"**Conditions:** {conditions}\n"
        f"**Exceptions:** {exceptions}"
    )

    content = content[:match.start()] + replacement + content[match.end():]
    RULES_FILE.write_text(content, encoding="utf-8")

    return {"message": f"Regra {rule_id} atualizada."}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8899)
